### ISSUE TITLE
Error on Maco OSX Sierra

### ISSUE THREAD

**Issue by tance77** [HardTacos/riot-games-api-nodejs#8]
index.js:188

    constructor(...apiKeys) {
                ^^^

SyntaxError: Unexpected token ...
    at exports.runInThisContext (vm.js:53:16)
    at Module._compile (module.js:387:25)
    at Object.Module._extensions..js (module.js:422:10)
    at Module.load (module.js:357:32)
    at Function.Module._load (module.js:314:12)
    at Module.require (module.js:367:17)
    at require (internal/module.js:16:19)

I get this error when I try to run on my mac, but it runs perfectly fine on windows.

**Comment by HardTacos** [comment]
@tance77 incase anyone else if having the issue, what did you do to resolve your problem?

**Comment by tance77** [comment]
It was a node js version problem
